require("integrations.aai-loaders")
require("integrations.deadlock-beltboxes-loaders")
require("integrations.prismatic-belts")
require("integrations.miniloader-redux")
require("integrations.belt-legacy")